const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

class UserModel {
  // Create a new user. ID is strictly generated by Prisma.
  static async createUser(userData) {
    const data = {
      fullName: userData.fullName,
      phone: userData.phone,
      email: userData.email || null,
      role: userData.role || 'PASSENGER',
      status: userData.status || 'ACTIVE',
      avatarUrl: userData.avatarUrl || null,
      ratingAvg: userData.ratingAvg || 5.0
    };
    
    // Explicitly ignoring userData.id to enforce system generation
    
    return await prisma.user.create({
      data
    });
  }

  // Find user by ID
  static async findUserById(userId) {
    if (!userId) {
      throw new Error('User ID must not be null');
    }
    return await prisma.user.findUnique({
      where: { id: userId }
    });
  }

  // Find user by phone
  static async findUserByPhone(phone) {
    return await prisma.user.findUnique({
      where: { phone }
    });
  }

  // Find all users (with pagination)
  static async findAllUsers(skip = 0, take = 10) {
    const [users, total] = await Promise.all([
      prisma.user.findMany({
        skip,
        take,
        orderBy: { createdAt: 'desc' }
      }),
      prisma.user.count()
    ]);

    return {
      data: users,
      total,
      skip,
      take
    };
  }

  // Update user
  static async updateUser(userId, updateData) {
    const data = {};
    if (updateData.fullName !== undefined) data.fullName = updateData.fullName;
    if (updateData.phone !== undefined) data.phone = updateData.phone;
    if (updateData.email !== undefined) data.email = updateData.email;
    if (updateData.avatarUrl !== undefined) data.avatarUrl = updateData.avatarUrl;
    if (updateData.role !== undefined) data.role = updateData.role;
    if (updateData.status !== undefined) data.status = updateData.status;
    if (updateData.ratingAvg !== undefined) data.ratingAvg = updateData.ratingAvg;

    return await prisma.user.update({
      where: { id: userId },
      data
    });
  }

  // Delete user
  static async deleteUser(userId) {
    return await prisma.user.delete({
      where: { id: userId }
    });
  }

  // Check if phone exists
  static async phoneExists(phone, excludeUserId = null) {
    const where = { phone };
    if (excludeUserId) {
      where.id = { not: excludeUserId };
    }
    const count = await prisma.user.count({ where });
    return count > 0;
  }

  // Find user by email
  static async findUserByEmail(email) {
    return await prisma.user.findUnique({
      where: { email }
    });
  }

  // Create user address
  static async createUserAddress(userId, addressData) {
    return await prisma.userAddress.create({
      data: {
        userId,
        label: addressData.label,
        address: addressData.address, // Required by schema
        lat: addressData.lat, // Required by schema
        lng: addressData.lng  // Required by schema
      }
    });
  }

  // Get user addresses
  static async getUserAddresses(userId) {
    return await prisma.userAddress.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' }
    });
  }

  // Update rating (called after review created event)
  static async updateUserRating(userId, newRating) {
    const user = await prisma.user.findUnique({
      where: { id: userId }
    });
    
    if (!user) return null;
    
    // Simple average calculation (in production, you'd fetch all reviews)
    return await prisma.user.update({
      where: { id: userId },
      data: {
        ratingAvg: newRating
      }
    });
  }
}

module.exports = UserModel;